graph LR
    APIGateway --> LambdaCriarPedido
    LambdaCriarPedido --> DynamoDB
    LambdaCriarPedido --> SQS
    SQS --> LambdaProcessarPedido
    LambdaProcessarPedido --> S3
    LambdaProcessarPedido --> SNS
    SNS --> NotificacaoParaCozinha
